### ISSUE TITLE
ROS 移植

### ISSUE THREAD

**Issue by jay16213** [TingYuanKe/EOY_NewRobot#1]
## 創建 ros package
note: 須先建立好 ros 的 workspace

```bash
cd ~/catkin_ws/src
catkin_create_pkg <package_name> std_msgs rospy roscpp
# ros建議: package_name 以英文小寫字母開頭, 且名稱僅包含英文小寫字母, 阿拉伯數字, 底線, dash
```

創好 package 後, 可在`~/catkin_ws/src/` 中看到 <package_name> 資料夾。
如 package name 叫 user_viewer (下文皆以 user_viewer 做為 package_name) 則整個 worksapce 結構應該如下
```
~/catkin_ws/
  src/
    user_viewer/
      include/
      src/
      package.xml
      CMakeLists.txt
    CMakeLists.txt
```

## 移植專案
1. 將需要的 code 放到 `~/catkin_ws/src/user_viewer/src`
2. 將 OpenNI, NiTE 的header file 放到 `~/catkin_ws/src/user_viewer/include`
3. 在 `~/catkin_ws/src/user_viewer` 下創兩個資料夾, `OpenNI2` & `NiTE2`, 將OpenNI, NiTE的 shared library (NiTE-Linux-x64-2.2/Redist & OpenNI-Linux-x64-2.2/Redist) 分別放入此兩個資料夾

4. 修改 `~/catkin_ws/src/user_viewer` 下的CMakeLists.txt (以下僅列出需要修改部份)

```cmake
...

find_package(OpenGL REQUIRED)
find_package(GLUT REQUIRED)

...

include_directories(
    include
    ${catkin_INCLUDE_DIRS}
    ${OPENGL_INCLUDE_DIRS}
    ${GLUT_INCLUDE_DIRS}
)

link_directories(
    NiTE2
    OpenNI2
)

add_executable(<node_name> src/main.cpp src/Viewer.cpp)

target_link_libraries(<node_name> ${catkin_LIBRARIES} ${OPENGL_LIBRARIES} ${GLUT_LIBRARY} OpenNI2 NiTE2)

...
```

## Compile
```bash
cd ~/catkin_ws
catkin_make
```

compile 成功後, 執行
```bash
source ~/catkin_ws/devel/setup.bash
```

確認 source 有無成功: 嘗試輸入下列指令, 若可按 tab 自動完成指令即表示成功:
```
rosrun user_viewer <node_name>
```

若專案確認沒問題, 可將 `~/catkin_ws/devel/setup.bash` 加入 `~/.bash.rc` 中, 以後就不用再 source 可直接執行 node
```bash
echo "source ~/catkin_ws/devel/setup.bash" >> ~/.bashrc
source ~/.bashrc
```

## Run the project
執行 ros 核心
```bash
roscore
```

開另一個 terminal, 執行
```bash
rosrun user_viewer <node_name>
```

note: 若找不到node, 先確認是否有先 source `~/catkin_ws/devel/setup.bash`

sample project: https://drive.google.com/open?id=1Y0C0dCQ-yKPjawByFzo2ICmKpXe6D4BX

**Comment by TingYuanKe** [comment]
哈囉學弟
我試著build起來看看
到了catkin_make這裡出現下面的錯誤

-- ==> add_subdirectory(user_viewer)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GLUT_Xmu_LIBRARY (ADVANCED)
    linked by target "UserViewer_node" in directory /home/newrobot/catkin_ws/src/user_viewer

看起來是glut的header檔沒有吃到
你們那時後有把GL的library和header塞到哪邊嘛？

## Solution
Install package
```
sudo apt-get install libxmu-dev libxi-dev
```

**Comment by jay16213** [comment]
我沒有特別去動OpengL跟glut的部份
想請你先確認在catkin_make時有無輸出下列兩行

```bash
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found GLUT: /usr/lib/x86_64-linux-gnu/libglut.so 
```

以及檢查
1 在/usr/lib/x86_64-linux-gnu/ 底下有無 libGL.so以及libglut.so這兩個檔案
2. /usr/include 底下有無GL/ 資料夾及裡面有無相對應的glut的header

底下附上完整的CMakeLists.txt
須注意 opengl 和 glut 的 find_package一定要分開寫成兩行
不可以直接加在ros原來的find_package中
```cmake
cmake_minimum_required(VERSION 2.8.3)
project(user_viewer)

## Compile as C++11, supported in ROS Kinetic and newer
# add_compile_options(-std=c++11)

## Find catkin macros and libraries
## if COMPONENTS list like find_package(catkin REQUIRED COMPONENTS xyz)
## is used, also find other catkin packages
find_package(catkin REQUIRED COMPONENTS
  roscpp
  rospy
  std_msgs
)

## System dependencies are found with CMake's conventions
# find_package(Boost REQUIRED COMPONENTS system)
find_package(OpenGL REQUIRED)
find_package(GLUT REQUIRED)

## Uncomment this if the package has a setup.py. This macro ensures
## modules and global scripts declared therein get installed
## See http://ros.org/doc/api/catkin/html/user_guide/setup_dot_py.html
# catkin_python_setup()

################################################
## Declare ROS messages, services and actions ##
################################################

## To declare and build messages, services or actions from within this
## package, follow these steps:
## * Let MSG_DEP_SET be the set of packages whose message types you use in
##   your messages/services/actions (e.g. std_msgs, actionlib_msgs, ...).
## * In the file package.xml:
##   * add a build_depend tag for "message_generation"
##   * add a build_depend and a exec_depend tag for each package in MSG_DEP_SET
##   * If MSG_DEP_SET isn't empty the following dependency has been pulled in
##     but can be declared for certainty nonetheless:
##     * add a exec_depend tag for "message_runtime"
## * In this file (CMakeLists.txt):
##   * add "message_generation" and every package in MSG_DEP_SET to
##     find_package(catkin REQUIRED COMPONENTS ...)
##   * add "message_runtime" and every package in MSG_DEP_SET to
##     catkin_package(CATKIN_DEPENDS ...)
##   * uncomment the add_*_files sections below as needed
##     and list every .msg/.srv/.action file to be processed
##   * uncomment the generate_messages entry below
##   * add every package in MSG_DEP_SET to generate_messages(DEPENDENCIES ...)

## Generate messages in the 'msg' folder
# add_message_files(
#   FILES
#   Message1.msg
#   Message2.msg
# )

## Generate services in the 'srv' folder
# add_service_files(
#   FILES
#   Service1.srv
#   Service2.srv
# )

## Generate actions in the 'action' folder
# add_action_files(
#   FILES
#   Action1.action
#   Action2.action
# )

## Generate added messages and services with any dependencies listed here
# generate_messages(
#   DEPENDENCIES
#   std_msgs
# )

################################################
## Declare ROS dynamic reconfigure parameters ##
################################################

## To declare and build dynamic reconfigure parameters within this
## package, follow these steps:
## * In the file package.xml:
##   * add a build_depend and a exec_depend tag for "dynamic_reconfigure"
## * In this file (CMakeLists.txt):
##   * add "dynamic_reconfigure" to
##     find_package(catkin REQUIRED COMPONENTS ...)
##   * uncomment the "generate_dynamic_reconfigure_options" section below
##     and list every .cfg file to be processed

## Generate dynamic reconfigure parameters in the 'cfg' folder
# generate_dynamic_reconfigure_options(
#   cfg/DynReconf1.cfg
#   cfg/DynReconf2.cfg
# )

###################################
## catkin specific configuration ##
###################################
## The catkin_package macro generates cmake config files for your package
## Declare things to be passed to dependent projects
## INCLUDE_DIRS: uncomment this if your package contains header files
## LIBRARIES: libraries you create in this project that dependent projects also need
## CATKIN_DEPENDS: catkin_packages dependent projects also need
## DEPENDS: system dependencies of this project that dependent projects also need
catkin_package(
#  INCLUDE_DIRS include
#  LIBRARIES UserViewer
#  CATKIN_DEPENDS roscpp rospy std_msgs
#  DEPENDS system_lib
)

###########
## Build ##
###########

## Specify additional locations of header files
## Your package locations should be listed before other locations
include_directories(
  include
  ${catkin_INCLUDE_DIRS}
  ${OPENGL_INCLUDE_DIRS}
  ${GLUT_INCLUDE_DIRS}
)

link_directories(
  NiTE2
  OpenNI2
)

## Declare a C++ library
# add_library(${PROJECT_NAME}
#   src/${PROJECT_NAME}/UserViewer.cpp
# )

## Add cmake target dependencies of the library
## as an example, code may need to be generated before libraries
## either from message generation or dynamic reconfigure
# add_dependencies(${PROJECT_NAME} ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})

## Declare a C++ executable
## With catkin_make all packages are built within a single CMake context
## The recommended prefix ensures that target names across packages don't collide
# add_executable(${PROJECT_NAME}_node src/UserViewer_node.cpp)
add_executable(UserViewer_node src/main.cpp src/Viewer.cpp)

## Rename C++ executable without prefix
## The above recommended prefix causes long target names, the following renames the
## target back to the shorter version for ease of user use
## e.g. "rosrun someones_pkg node" instead of "rosrun someones_pkg someones_pkg_node"
# set_target_properties(${PROJECT_NAME}_node PROPERTIES OUTPUT_NAME node PREFIX "")

## Add cmake target dependencies of the executable
## same as for the library above
# add_dependencies(${PROJECT_NAME}_node ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})

## Specify libraries to link a library or executable target against
# target_link_libraries(${PROJECT_NAME}_node
#   ${catkin_LIBRARIES}
# )
target_link_libraries(UserViewer_node ${catkin_LIBRARIES} ${OPENGL_LIBRARIES} ${GLUT_LIBRARY} OpenNI2 NiTE2)
#############
## Install ##
#############

# all install targets should use catkin DESTINATION variables
# See http://ros.org/doc/api/catkin/html/adv_user_guide/variables.html

## Mark executable scripts (Python etc.) for installation
## in contrast to setup.py, you can choose the destination
# install(PROGRAMS
#   scripts/my_python_script
#   DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
# )

## Mark executables and/or libraries for installation
# install(TARGETS ${PROJECT_NAME} ${PROJECT_NAME}_node
#   ARCHIVE DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
#   LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
#   RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
# )

## Mark cpp header files for installation
# install(DIRECTORY include/${PROJECT_NAME}/
#   DESTINATION ${CATKIN_PACKAGE_INCLUDE_DESTINATION}
#   FILES_MATCHING PATTERN "*.h"
#   PATTERN ".svn" EXCLUDE
# )

## Mark other files for installation (e.g. launch and bag files, etc.)
# install(FILES
#   # myfile1
#   # myfile2
#   DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
# )

#############
## Testing ##
#############

## Add gtest based cpp test target and link libraries
# catkin_add_gtest(${PROJECT_NAME}-test test/test_UserViewer.cpp)
# if(TARGET ${PROJECT_NAME}-test)
#   target_link_libraries(${PROJECT_NAME}-test ${PROJECT_NAME})
# endif()

## Add folders to be run by python nosetests
# catkin_add_nosetests(test)
```

**Comment by TingYuanKe** [comment]
> 我沒有特別去動OpengL跟glut的部份
> 想請你先確認在catkin_make時有無輸出下列兩行
> 
> ```shell
> -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
> -- Found GLUT: /usr/lib/x86_64-linux-gnu/libglut.so 
> ```
> 
> 以及檢查
> 1 在/usr/lib/x86_64-linux-gnu/ 底下有無 libGL.so以及libglut.so這兩個檔案
> 2. /usr/include 底下有無GL/ 資料夾及裡面有無相對應的glut的header
> 
> 底下附上完整的CMakeLists.txt
> 須注意 opengl 和 glut 的 find_package一定要分開寫成兩行
> 不可以直接加在ros原來的find_package中
> 
> ```cmake
> cmake_minimum_required(VERSION 2.8.3)
> project(user_viewer)
> 
> ## Compile as C++11, supported in ROS Kinetic and newer
> # add_compile_options(-std=c++11)
> 
> ## Find catkin macros and libraries
> ## if COMPONENTS list like find_package(catkin REQUIRED COMPONENTS xyz)
> ## is used, also find other catkin packages
> find_package(catkin REQUIRED COMPONENTS
>   roscpp
>   rospy
>   std_msgs
> )
> 
> ## System dependencies are found with CMake's conventions
> # find_package(Boost REQUIRED COMPONENTS system)
> find_package(OpenGL REQUIRED)
> find_package(GLUT REQUIRED)
> 
> ## Uncomment this if the package has a setup.py. This macro ensures
> ## modules and global scripts declared therein get installed
> ## See http://ros.org/doc/api/catkin/html/user_guide/setup_dot_py.html
> # catkin_python_setup()
> 
> ################################################
> ## Declare ROS messages, services and actions ##
> ################################################
> 
> ## To declare and build messages, services or actions from within this
> ## package, follow these steps:
> ## * Let MSG_DEP_SET be the set of packages whose message types you use in
> ##   your messages/services/actions (e.g. std_msgs, actionlib_msgs, ...).
> ## * In the file package.xml:
> ##   * add a build_depend tag for "message_generation"
> ##   * add a build_depend and a exec_depend tag for each package in MSG_DEP_SET
> ##   * If MSG_DEP_SET isn't empty the following dependency has been pulled in
> ##     but can be declared for certainty nonetheless:
> ##     * add a exec_depend tag for "message_runtime"
> ## * In this file (CMakeLists.txt):
> ##   * add "message_generation" and every package in MSG_DEP_SET to
> ##     find_package(catkin REQUIRED COMPONENTS ...)
> ##   * add "message_runtime" and every package in MSG_DEP_SET to
> ##     catkin_package(CATKIN_DEPENDS ...)
> ##   * uncomment the add_*_files sections below as needed
> ##     and list every .msg/.srv/.action file to be processed
> ##   * uncomment the generate_messages entry below
> ##   * add every package in MSG_DEP_SET to generate_messages(DEPENDENCIES ...)
> 
> ## Generate messages in the 'msg' folder
> # add_message_files(
> #   FILES
> #   Message1.msg
> #   Message2.msg
> # )
> 
> ## Generate services in the 'srv' folder
> # add_service_files(
> #   FILES
> #   Service1.srv
> #   Service2.srv
> # )
> 
> ## Generate actions in the 'action' folder
> # add_action_files(
> #   FILES
> #   Action1.action
> #   Action2.action
> # )
> 
> ## Generate added messages and services with any dependencies listed here
> # generate_messages(
> #   DEPENDENCIES
> #   std_msgs
> # )
> 
> ################################################
> ## Declare ROS dynamic reconfigure parameters ##
> ################################################
> 
> ## To declare and build dynamic reconfigure parameters within this
> ## package, follow these steps:
> ## * In the file package.xml:
> ##   * add a build_depend and a exec_depend tag for "dynamic_reconfigure"
> ## * In this file (CMakeLists.txt):
> ##   * add "dynamic_reconfigure" to
> ##     find_package(catkin REQUIRED COMPONENTS ...)
> ##   * uncomment the "generate_dynamic_reconfigure_options" section below
> ##     and list every .cfg file to be processed
> 
> ## Generate dynamic reconfigure parameters in the 'cfg' folder
> # generate_dynamic_reconfigure_options(
> #   cfg/DynReconf1.cfg
> #   cfg/DynReconf2.cfg
> # )
> 
> ###################################
> ## catkin specific configuration ##
> ###################################
> ## The catkin_package macro generates cmake config files for your package
> ## Declare things to be passed to dependent projects
> ## INCLUDE_DIRS: uncomment this if your package contains header files
> ## LIBRARIES: libraries you create in this project that dependent projects also need
> ## CATKIN_DEPENDS: catkin_packages dependent projects also need
> ## DEPENDS: system dependencies of this project that dependent projects also need
> catkin_package(
> #  INCLUDE_DIRS include
> #  LIBRARIES UserViewer
> #  CATKIN_DEPENDS roscpp rospy std_msgs
> #  DEPENDS system_lib
> )
> 
> ###########
> ## Build ##
> ###########
> 
> ## Specify additional locations of header files
> ## Your package locations should be listed before other locations
> include_directories(
>   include
>   ${catkin_INCLUDE_DIRS}
>   ${OPENGL_INCLUDE_DIRS}
>   ${GLUT_INCLUDE_DIRS}
> )
> 
> link_directories(
>   NiTE2
>   OpenNI2
> )
> 
> ## Declare a C++ library
> # add_library(${PROJECT_NAME}
> #   src/${PROJECT_NAME}/UserViewer.cpp
> # )
> 
> ## Add cmake target dependencies of the library
> ## as an example, code may need to be generated before libraries
> ## either from message generation or dynamic reconfigure
> # add_dependencies(${PROJECT_NAME} ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})
> 
> ## Declare a C++ executable
> ## With catkin_make all packages are built within a single CMake context
> ## The recommended prefix ensures that target names across packages don't collide
> # add_executable(${PROJECT_NAME}_node src/UserViewer_node.cpp)
> add_executable(UserViewer_node src/main.cpp src/Viewer.cpp)
> 
> ## Rename C++ executable without prefix
> ## The above recommended prefix causes long target names, the following renames the
> ## target back to the shorter version for ease of user use
> ## e.g. "rosrun someones_pkg node" instead of "rosrun someones_pkg someones_pkg_node"
> # set_target_properties(${PROJECT_NAME}_node PROPERTIES OUTPUT_NAME node PREFIX "")
> 
> ## Add cmake target dependencies of the executable
> ## same as for the library above
> # add_dependencies(${PROJECT_NAME}_node ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})
> 
> ## Specify libraries to link a library or executable target against
> # target_link_libraries(${PROJECT_NAME}_node
> #   ${catkin_LIBRARIES}
> # )
> target_link_libraries(UserViewer_node ${catkin_LIBRARIES} ${OPENGL_LIBRARIES} ${GLUT_LIBRARY} OpenNI2 NiTE2)
> #############
> ## Install ##
> #############
> 
> # all install targets should use catkin DESTINATION variables
> # See http://ros.org/doc/api/catkin/html/adv_user_guide/variables.html
> 
> ## Mark executable scripts (Python etc.) for installation
> ## in contrast to setup.py, you can choose the destination
> # install(PROGRAMS
> #   scripts/my_python_script
> #   DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
> # )
> 
> ## Mark executables and/or libraries for installation
> # install(TARGETS ${PROJECT_NAME} ${PROJECT_NAME}_node
> #   ARCHIVE DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
> #   LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
> #   RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
> # )
> 
> ## Mark cpp header files for installation
> # install(DIRECTORY include/${PROJECT_NAME}/
> #   DESTINATION ${CATKIN_PACKAGE_INCLUDE_DESTINATION}
> #   FILES_MATCHING PATTERN "*.h"
> #   PATTERN ".svn" EXCLUDE
> # )
> 
> ## Mark other files for installation (e.g. launch and bag files, etc.)
> # install(FILES
> #   # myfile1
> #   # myfile2
> #   DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
> # )
> 
> #############
> ## Testing ##
> #############
> 
> ## Add gtest based cpp test target and link libraries
> # catkin_add_gtest(${PROJECT_NAME}-test test/test_UserViewer.cpp)
> # if(TARGET ${PROJECT_NAME}-test)
> #   target_link_libraries(${PROJECT_NAME}-test ${PROJECT_NAME})
> # endif()
> 
> ## Add folders to be run by python nosetests
> # catkin_add_nosetests(test)
> ```

**Comment by TingYuanKe** [comment]
#### **Issue**
執行```rosrun user_viewer <node_name>```出現
```
Could not find data file ./NiTE2/h.dat
current working directory = /home/newrobot/catkin_ws
```
吃不到 /NiTE2/NiTE2 裡的 **s.dat**和 **h.dat**

#### Solution:
將NiTE2/NiTE2 lib folder duplicate 一份至 **catkin_ws**

**Comment by edwardwang-nycu** [comment]
In C++, you can use ros::package in the roslib package to get information about ROS packages. For example:

#include <ros/package.h>

...

  std::string path = ros::package::getPath("roslib");
